### ISSUE TITLE
Build exe

### ISSUE THREAD

**Issue by jddaigle** [pgate1/spcmake_byFF6#1]
Hello! how can I build the exe from the source code. What compiler/EDI are you using?

Thanks a lot!

**Comment by pgate1** [comment]
Thanks for the input.

The compiler used to generate the exe is VC++6.0.

I would like to modify the source code so that it can be compiled in VS2017.

**Comment by jddaigle** [comment]
Thanks a lot! but doesn't work 😭
I just created a new project in VC++ 6.0 and added the cpp files
![image](https://user-images.githubusercontent.com/521601/104052645-0387dd00-51b8-11eb-8f25-f9736d0ab314.png)

 I flag the cpp to "Not using precompiled headers"
![image](https://user-images.githubusercontent.com/521601/104052400-ab50db00-51b7-11eb-9d6e-5c9fca4414b0.png)
To get rid of the "fatal error C1010: unexpected end of file while looking for precompiled header directive"

And now I get these errors:

--------------------Configuration: SPCMAKE_FF6 - Win32 Debug--------------------
Compiling...
brr2wav.cpp
Compiling...
spcmake_byFF6.cpp
Linking...
spcmake_byFF6.obj : error LNK2005: "class std::vector<short,class std::allocator<short> > __cdecl decode_brr(unsigned char const *,int,bool *)" (?decode_brr@@YA?AV?$vector@FV?$allocator@F@std@@@std@@PBEHPA_N@Z) already defined in brr2wav.obj
spcmake_byFF6.obj : error LNK2005: "public: void __thiscall WavWriter::AddSample(short)" (?AddSample@WavWriter@@QAEXF@Z) already defined in brr2wav.obj
spcmake_byFF6.obj : error LNK2005: "public: void __thiscall WavWriter::AddSample(class std::vector<short,class std::allocator<short> >)" (?AddSample@WavWriter@@QAEXV?$vector@FV?$allocator@F@std@@@std@@@Z) already defined in brr2wav.obj
spcmake_byFF6.obj : error LNK2005: "public: bool __thiscall WavWriter::WriteFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?WriteFile@WavWriter@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V
?$allocator@D@2@@std@@@Z) already defined in brr2wav.obj
spcmake_byFF6.obj : error LNK2005: "int __cdecl brr2wav(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char const *,int,unsigned short,unsigned short)" (?brr2wav@@YAHABV?$basic_string@DU?$cha
r_traits@D@std@@V?$allocator@D@2@@std@@PBEHGG@Z) already defined in brr2wav.obj
Debug/SPCMAKE_FF6.exe : fatal error LNK1169: one or more multiply defined symbols found
Error executing link.exe.

SPCMAKE_FF6.exe - 6 error(s), 0 warning(s)

What should I do ... does my setup is ok?

**Comment by pgate1** [comment]
Exclude brr2wav.cpp from the Source Files of your project. It is included directly in spcmake_byFF6.cpp.

**Comment by pgate1** [comment]
Fixed so that it can be compiled in VS2017.

**Comment by jddaigle** [comment]
It works on VC++ 6!

Thanks a lot... now I'm trying on VS 2017
